# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['zrl_terminal.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icons/*', 'icons/'),
        ('fileicon.ico', '.'),
    ],
    hiddenimports=[
        'turtle',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.font',
        'tkinter.colorchooser',
        'tkinter.simpledialog',
        'tkinter.dnd',
        'pickle',
        'argparse',
        'readline',
        'math',
        'time',
        'random',
        'datetime',
        'shutil',
        'json',
        'base64',
        'urllib.request',
        'urllib.parse',
        'tempfile',
        'subprocess',
        'psutil',
        'atexit',
        'codecs',
        'zrl_lexer',
        'zrl_parser',
        'zrl_interpreter',
        'zrl_stdlib',
        'zrl_terminal',
        'zrl_compiler',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ZRLterminal',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icons/icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ZRLterminal',
)